### ISSUE TITLE
REST API does not return Product custom fields - Product Properties

### ISSUE THREAD

**Issue by drmDev** [woothemes/wc-api-python#10]
We have custom fields added to our products under WooCommerce > Custom Fields > Product Properties. When I do a get request on a product with those properties such as:

r = api.get("products/37")
or r = wcapi.get("products/37?filter[meta]=true")

The JSON returned does not include these custom fields or their values.

How can I retrieve these Product custom fields by the API?

**Comment by claudiosmweb** [comment]
Not a problem in this wrapper and I answered your question in another repository.
