### ISSUE TITLE
Invalid Signature - provided signature does not match

### ISSUE THREAD

**Issue by chbichsel** [woothemes/wc-api-python#13]
Hi, 

I am getting an invalid signature exception (400) using the Setup for the old WooCommerce API v3 example in the documentation (getting a 404 with the P REST API, but that's a separate issue). 

I read up on all related issues & solutions regarding woothemes API I could find , but  I am not able to figure out what is going wrong. Any pointers?

. {"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}

string_to_sign = 
GET&http%3A%2F%2Fdigitalsystems4dev.com%2Fwc-api%2Fv3%2Fproducts&oauth_consumer_key%***%26oauth_nonce%***%26oauth_signature_method%3DHMAC-SHA256%26oauth_timestamp%3D1463680922

query_string = oauth_consumer_key=c***&oauth_timestamp=1463683292&oauth_nonce=750657abcf2e03a85fd1acfb965d806be291daca&oauth_signature_method=HMAC-SHA256&oauth_signature=UKdq5Vm0YDTmZ2LtnKj2%2F%2FIrrYRj3MCRytJt0VQ7ZZ4%3D

URL
http://digitalsystems4dev.com/wc-api/wc/v3/products?oauth_consumer_key=ck_8d60fb00cc4c1a7da8df182c01f6aaa24eabb423&oauth_timestamp=1463683474&oauth_nonce=cbb609be40c3eb5a0d99213d3a79cd3559ffade7&oauth_signature_method=HMAC-SHA256&oauth_signature=idndeHBygNPp2KMVQpedb6SkDJ8PB4UHWLKlbhr8wiI%3D

**Comment by chbichsel** [comment]
I tried the same with a SSL domain on bluehost (rather than godaddy as above). I am getting a 400 as well. 

When I use curl, the test product comes back correctly: curl https://www.example.com/wc-api/v3/orders  -u consumer_key:consumer_secret

**Comment by chbichsel** [comment]
Turns out I was using version="wc/v3", but connected to the  old WooCommerce API v3. As a result, the URL had wc/v3 in the path which doesn't exist https://kashalife-beta.com/wc-api/wc/v3/products

**Comment by claudiosmweb** [comment]
For the old API we can use one `version="v3"`
