### ISSUE TITLE
No route was found matching the URL and request method

### ISSUE THREAD

**Issue by bsteph** [woothemes/wc-api-python#15]
Very simple test doesn't seem to be working.  

import sys
from woocommerce import API

wcapi = API(
    url="https://<my host>",
    consumer_key="ck_blahblahblah",
    consumer_secret="cs_blahblahblah",
    wp_api=True,
    version="wc/v1"
)
print(wcapi.get("products").json())

returns {u'message': u'No route was found matching the URL and request method', u'code': u'rest_no_route', u'data': {u'status': 404}}

However, when run the following command I get a good return:
curl "https://<Myurl>/wc-api/v3/products?consumer_key=ck_blahblahblah&consumer_secret=cs_blahblahblah&wp_api=True&version=wc/v2&search=ATIGFX45GI"

**Comment by claudiosmweb** [comment]
Are you using WooCommerce 2.6?
Because only WooCommerce 2.6 have integration with WP REST API like you are using in your settings `wp_api=True, version="wc/v1"` ;)
