### ISSUE TITLE
GET Product/Categories

### ISSUE THREAD

**Issue by marianoduran** [woothemes/wc-api-python#18]
While trying to get all product/Categories from Woocommerce I am only getting a few instead of the 500 Categories that I have created programmatically. Any advice?

I am executing the follow code from Python
"...
wcapi = API(
    url="http://99.99.99.99",
    consumer_key="ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    consumer_secret="cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    wp_api=True,
    version="wc/v1"
  )
r = wcapi.get("products/categories/")
r.json()
..."

Have seen that there is a parameter called "per_page" to determine the maximum number of items to be returned in result set. How should I apply in the code above?

Regards,
Mariano

**Comment by claudiosmweb** [comment]
> I am only getting a few instead of the 500 Categories that I have created programmatically

Don't seems like a issue in this wrapper, so I'm closing.
If you have questions about how the REST API works, you should try https://wordpress.org/support/plugin/woocommerce

**Comment by jdruiter** [comment]
@marianoduran  
wcapi.get("products/categories?per_page=20")
wcapi.get("products/categories?page=2")
wcapi.get("products/categories?page=3")
