### ISSUE TITLE
Performing pagination

### ISSUE THREAD

**Issue by acquayefrank** [woothemes/wc-api-python#2]
This might not be the right place, but I'm wondering how to perform pagination with the python wrapper for woocommerce

**Comment by claudiosmweb** [comment]
http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by acquayefrank** [comment]
I did look through the docs, but it was quite unclear to me.  eg
How do I perform such a request with the wrapper GET /orders?page=2

**Comment by claudiosmweb** [comment]
Yes, `wcapi.get("/orders?page=2 ")`

**Comment by acquayefrank** [comment]
I tried that, but I get this error:

for key, value in urlparse.parse_qsl(urlparse.urlparse(self.url).query):
AttributeError: 'function' object has no attribute 'parse_qsl'

**Comment by claudiosmweb** [comment]
@acquayefrank update to 1.0.2

**Comment by acquayefrank** [comment]
Thanks. But what worked for me after upgrading was   wcapi.get("orders?page=2")

**Comment by bh** [comment]
```python
>>> len(wcapi.get("products?filter[limit]=100").json()["products"])
100
```
works for me. Had no success with `?per_page=`.

**Comment by claudiosanches** [comment]
@bh please check the docs: https://woocommerce.github.io/woocommerce-rest-api-docs/
