### ISSUE TITLE
Can't use OAuth (API calls over HTTP)

### ISSUE THREAD

**Issue by Djiit** [woothemes/wc-api-python#3]
Hi, 

Tested with versions 1.0.1 and 1.0.2, I can't use this library over HTTP. It seems to be related to the OAuth signature generated by the OAuth class.

Here is my code (adapted from the README example) : 

    wcapi = API(
        url="http://0.0.0.0:8080",
        consumer_key=WC_API_KEY,
        consumer_secret=WC_API_SECRET,
        version="v2",
        verify_ssl=False
    )
    
    r = wcapi.get("products")
     
    print(r.status_code)
    print(r.text)

Here is the return :

    401
    {'errors': [{'code': 'woocommerce_api_authentication_error', 'message': 'Signature invalide - la signature fournie ne correspond pas'}]}

(I'm using a French translation of WooCommerce)

Do I need to force the use of OAuth1 somewhere ?

Thanks for your help

**Comment by claudiosmweb** [comment]
Nop, just use http and will works fine.
The `verify_ssl` will works just when you use `https`.

**Comment by Djiit** [comment]
Hi,

Sorry but no, It doesn't work fine when using HTTP. I don't see any tests related to your oauthlib usage and WooCommerce keeps telling me I don't provide a valid signature.

I have this error on Ubuntu 14.04 LTS with Python3.4 (also tested with py3.3, same result).

Thx

**Comment by claudiosmweb** [comment]
@Djiit Can not write tests for it, as the nonces will always be different:
https://github.com/woothemes/wc-api-python/blob/master/woocommerce/oauth.py#L53-L57

Here to you that me saying I'm a liar: https://cloudup.com/cWGk0Pct9ww

![screenshot from 2015-08-06 08 51 50](https://cloud.githubusercontent.com/assets/1264099/9110952/96417ac2-3c18-11e5-8d68-96662f278019.png)

In other words: IT WORKS and you are doing something wrong!

**Comment by Djiit** [comment]
Hi,

I didn't say you are a liar... Just trying to figure out what I could have missed.
In your screencast, you are using the "v3" API... Which I don't have in my WooCommerce installation. (only "v1" and "v2"). Can it be related to the version I use ?

Thx

**Comment by claudiosmweb** [comment]
@Djiit I show an example of v2 too!
But v2 and v3 have different authentication methods... In v2 some specs of Oauth 1.0a were ignored and everything was fixed in v3.
