### ISSUE TITLE
Basic import doesn't work

### ISSUE THREAD

**Issue by davehodg** [woothemes/wc-api-python#79]
from woocommerce import API

Gives:

ImportError: cannot import name 'API' from partially initialized module 'woocommerce' (most likely due to a circular import) (/Users/daveh/workspace/mine/xxx/woocommerce.py)

**Comment by chichi13** [comment]
It's because your filename is `woocommerce.py` and you try to import `from woocommerce`. So it tries to import the file and not the package.
Rename your file `main.py` or something different

**Comment by davehodg** [comment]
Yep. I worked that out.
